name: Docker Build and Run on AWS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_REGION: ap-northeast-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::384303226177:role/rails-app-github-action-role
          aws-region: ap-northeast-1
        outputs:
          registry: ${{ steps.login-ecr.outputs.registry }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ needs.login-to-amazon-ecr.outputs.registry }}/rails-deploy-test:${{ github.sha }}

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS instance
        env:
          DOCKER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/your-ecr-repo:${{ github.sha }}
        run: |
          scp -i private_key docker-compose.yml ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/app
          ssh -i private_key ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "cd /path/to/your/app && docker-compose down && docker-compose up -d"
